name: GitHub Metrics

on:
  schedule:
    - cron: "0 * * * *" # Runs every hour
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: dev-zeb
          template: classic
          base: header, activity
          config_timezone: Asia/Dhaka
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          plugin_activity: yes
          plugin_activity_limit: 5
          plugin_activity_visibility: all
          plugin_activity_filter: issue, pr, push
          plugin_repositories: yes
          plugin_lines: yes
          plugin_traffic: yes
          plugin_followup: yes
